// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // AMEEN: Ameen's Firebase project (ameen-zaidshaikh)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8GbrE-j2F7Fu8YIo8CZo3JCrQJ6Ptaf4',
    appId: '1:574981835110:web:3e886498f6fa65704d60a7',
    messagingSenderId: '574981835110',
    projectId: 'ameen-zaidshaikh',
    authDomain: 'ameen-zaidshaikh.firebaseapp.com',
    storageBucket: 'ameen-zaidshaikh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOogUJw5Z1wt9QG_9HWWKZHSO5zK0xmog',
    appId: '1:574981835110:android:6ab14e7cf967bb6d4d60a7',
    messagingSenderId: '574981835110',
    projectId: 'ameen-zaidshaikh',
    storageBucket: 'ameen-zaidshaikh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBts7THLrbIh-xReN70k5AsknAMwBNhrD0',
    appId: '1:267621253497:ios:17af91fbac7c01b9842fa8',
    messagingSenderId: '267621253497',
    projectId: 'budget-app-flutter',
    storageBucket: 'budget-app-flutter.appspot.com',
    androidClientId: '267621253497-0h976snjlf34gs8m75bh8nik8gcvr2mk.apps.googleusercontent.com',
    iosClientId: '267621253497-ih94g1srq37gun4mdmvadgl3ev588vpf.apps.googleusercontent.com',
    iosBundleId: 'com.budget.tracker-app',
  );
}
