import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';

// Material Symbols (Rounded) icons that can be picked for categories, goals and
// accounts, next to upstream's PNG icons and emoji.
//
// Stored in the existing iconName columns as "ms:<name>", so no database schema
// change is needed. Icons are referenced as consts so icon tree shaking still
// only bundles the glyphs listed here.

const String materialIconPrefix = "ms:";

// Any icon Ameen draws itself instead of an upstream asset PNG
bool isAmeenIcon(String? iconName) =>
    isMaterialIcon(iconName) || (iconName?.startsWith("img:") ?? false);

bool isMaterialIcon(String? iconName) =>
    iconName != null && iconName.startsWith(materialIconPrefix);

String materialIconNameToStore(String name) => materialIconPrefix + name;

IconData? materialIconFor(String? iconName) {
  if (iconName == null) return null;
  String name = iconName.startsWith(materialIconPrefix)
      ? iconName.substring(materialIconPrefix.length)
      : iconName;
  return materialIconsByName[name]?.icon;
}

class MaterialIconForCategory {
  const MaterialIconForCategory(
      this.name, this.icon, this.mostLikelyCategoryName, this.tags);
  final String name;
  final IconData icon;
  final String mostLikelyCategoryName;
  final List<String> tags;
}

final Map<String, MaterialIconForCategory> materialIconsByName = {
  for (MaterialIconForCategory entry in materialIconCatalog) entry.name: entry
};

List<MaterialIconForCategory> searchMaterialIcons(String search) {
  String query = search.trim().toLowerCase();
  if (query == "") return materialIconCatalog;
  return materialIconCatalog.where((entry) {
    if (entry.name.replaceAll("_", " ").contains(query)) return true;
    if (entry.mostLikelyCategoryName.toLowerCase().contains(query)) return true;
    for (String tag in entry.tags) {
      if (tag.contains(query)) return true;
    }
    return false;
  }).toList();
}

class MaterialIconSection {
  const MaterialIconSection(this.key, this.title, this.icons);
  final String key;
  // English title, translated with "icon-section-<key>" when available
  final String title;
  final List<MaterialIconForCategory> icons;
}

typedef _I = MaterialIconForCategory;

// Sections shown as headings in the picker, in this order
const List<MaterialIconSection> materialIconSections = [
  MaterialIconSection("money", "Money & Banking", [
    _I("account_balance", Symbols.account_balance_rounded, "Bank", ["bank", "account", "building"]),
    _I("account_balance_wallet", Symbols.account_balance_wallet_rounded, "Wallet", ["wallet", "cash", "account"]),
    _I("wallet", Symbols.wallet_rounded, "Wallet", ["wallet", "purse", "cash"]),
    _I("payments", Symbols.payments_rounded, "Cash", ["cash", "money", "notes", "bills"]),
    _I("money", Symbols.money_rounded, "Cash", ["cash", "money", "notes"]),
    _I("attach_money", Symbols.attach_money_rounded, "Money", ["dollar", "money", "income"]),
    _I("currency_exchange", Symbols.currency_exchange_rounded, "Exchange", ["exchange", "forex", "transfer"]),
    _I("credit_card", Symbols.credit_card_rounded, "Credit Card", ["card", "credit", "visa", "mastercard"]),
    _I("credit_score", Symbols.credit_score_rounded, "Credit", ["credit", "score", "card"]),
    _I("add_card", Symbols.add_card_rounded, "Card", ["card", "debit", "new"]),
    _I("contactless", Symbols.contactless_rounded, "Tap to Pay", ["contactless", "nfc", "tap", "pay"]),
    _I("savings", Symbols.savings_rounded, "Savings", ["savings", "piggy", "bank", "save"]),
    _I("price_check", Symbols.price_check_rounded, "Bills", ["price", "check", "paid"]),
    _I("receipt_long", Symbols.receipt_long_rounded, "Bills", ["receipt", "bill", "invoice"]),
    _I("receipt", Symbols.receipt_rounded, "Receipt", ["receipt"]),
    _I("request_quote", Symbols.request_quote_rounded, "Quote", ["quote", "invoice", "document"]),
    _I("sell", Symbols.sell_rounded, "Sales", ["sale", "tag", "price"]),
    _I("local_atm", Symbols.local_atm_rounded, "ATM", ["atm", "cash", "withdraw"]),
    _I("atm", Symbols.atm_rounded, "ATM", ["atm", "cash", "withdraw"]),
    _I("point_of_sale", Symbols.point_of_sale_rounded, "Shop", ["pos", "register", "checkout"]),
    _I("paid", Symbols.paid_rounded, "Paid", ["paid", "coin", "money"]),
    _I("toll", Symbols.toll_rounded, "Tolls", ["toll", "coins", "salik"]),
    _I("monetization_on", Symbols.monetization_on_rounded, "Income", ["income", "coin", "money"]),
    _I("universal_currency", Symbols.universal_currency_rounded, "Universal Currency", ["universal", "currency"]),
    _I("universal_currency_alt", Symbols.universal_currency_alt_rounded, "Currency", ["currency", "money"]),
    _I("euro", Symbols.euro_rounded, "Euro", ["euro"]),
    _I("currency_pound", Symbols.currency_pound_rounded, "Currency Pound", ["currency", "pound"]),
    _I("currency_rupee", Symbols.currency_rupee_rounded, "Currency Rupee", ["currency", "rupee"]),
    _I("currency_yen", Symbols.currency_yen_rounded, "Currency Yen", ["currency", "yen"]),
    _I("currency_franc", Symbols.currency_franc_rounded, "Currency Franc", ["currency", "franc"]),
    _I("currency_lira", Symbols.currency_lira_rounded, "Currency Lira", ["currency", "lira"]),
    _I("currency_ruble", Symbols.currency_ruble_rounded, "Currency Ruble", ["currency", "ruble"]),
    _I("currency_yuan", Symbols.currency_yuan_rounded, "Currency Yuan", ["currency", "yuan"]),
    _I("currency_bitcoin", Symbols.currency_bitcoin_rounded, "Crypto", ["bitcoin", "crypto"]),
    _I("send_money", Symbols.send_money_rounded, "Remittance", ["remittance", "send money", "transfer", "home"]),
    _I("request_page", Symbols.request_page_rounded, "Statements", ["statement", "page"]),
    _I("swap_horiz", Symbols.swap_horiz_rounded, "Transfers", ["transfer", "swap"]),
    _I("sync_alt", Symbols.sync_alt_rounded, "Transfers", ["transfer", "sync"]),
    _I("price_change", Symbols.price_change_rounded, "Price Change", ["price", "change"]),
    _I("payment", Symbols.payment_rounded, "Payment", ["payment"]),
    _I("card_membership", Symbols.card_membership_rounded, "Card Membership", ["card", "membership"]),
    _I("qr_code_2", Symbols.qr_code_2_rounded, "Qr Code 2", ["qr", "code"]),
    _I("qr_code_scanner", Symbols.qr_code_scanner_rounded, "Qr Code Scanner", ["qr", "code", "scanner"]),
    _I("barcode_scanner", Symbols.barcode_scanner_rounded, "Barcode Scanner", ["barcode", "scanner"]),
    _I("autopay", Symbols.autopay_rounded, "Autopay", ["autopay"]),
    _I("checkbook", Symbols.checkbook_rounded, "Checkbook", ["checkbook"]),
    _I("smart_card_reader", Symbols.smart_card_reader_rounded, "Smart Card Reader", ["smart", "card", "reader"]),
    _I("credit_card_clock", Symbols.credit_card_clock_rounded, "Credit Card Clock", ["credit", "card", "clock"]),
    _I("credit_card_heart", Symbols.credit_card_heart_rounded, "Credit Card Heart", ["credit", "card", "heart"]),
    _I("credit_card_gear", Symbols.credit_card_gear_rounded, "Credit Card Gear", ["credit", "card", "gear"]),
    _I("cards", Symbols.cards_rounded, "Cards", ["cards"]),
    _I("nest_found_savings", Symbols.nest_found_savings_rounded, "Nest Found Savings", ["nest", "found", "savings"]),
    _I("barcode", Symbols.barcode_rounded, "Barcode", ["barcode"]),
    _I("order_approve", Symbols.order_approve_rounded, "Order Approve", ["order", "approve"]),
    _I("contract", Symbols.contract_rounded, "Contract", ["contract"]),
    _I("contract_edit", Symbols.contract_edit_rounded, "Contract Edit", ["contract", "edit"]),
    _I("approval_delegation", Symbols.approval_delegation_rounded, "Approval Delegation", ["approval", "delegation"]),
  ]),
  MaterialIconSection("invest", "Investing & Savings", [
    _I("trending_up", Symbols.trending_up_rounded, "Investments", ["invest", "stocks", "growth"]),
    _I("trending_down", Symbols.trending_down_rounded, "Trending Down", ["trending", "down"]),
    _I("show_chart", Symbols.show_chart_rounded, "Stocks", ["stocks", "chart", "market"]),
    _I("candlestick_chart", Symbols.candlestick_chart_rounded, "Trading", ["trading", "stocks", "crypto"]),
    _I("pie_chart", Symbols.pie_chart_rounded, "Portfolio", ["portfolio", "chart"]),
    _I("donut_large", Symbols.donut_large_rounded, "Donut Large", ["donut", "large"]),
    _I("bar_chart", Symbols.bar_chart_rounded, "Bar Chart", ["bar", "chart"]),
    _I("stacked_line_chart", Symbols.stacked_line_chart_rounded, "Stacked Line Chart", ["stacked", "line", "chart"]),
    _I("analytics", Symbols.analytics_rounded, "Analytics", ["analytics"]),
    _I("insights", Symbols.insights_rounded, "Insights", ["insights"]),
    _I("query_stats", Symbols.query_stats_rounded, "Query Stats", ["query", "stats"]),
    _I("finance", Symbols.finance_rounded, "Finance", ["finance"]),
    _I("finance_chip", Symbols.finance_chip_rounded, "Finance Chip", ["finance", "chip"]),
    _I("diamond", Symbols.diamond_rounded, "Valuables", ["diamond", "jewelry", "luxury"]),
    _I("workspace_premium", Symbols.workspace_premium_rounded, "Gold", ["gold", "premium", "badge"]),
    _I("military_tech", Symbols.military_tech_rounded, "Military Tech", ["military", "tech"]),
    _I("emoji_events", Symbols.emoji_events_rounded, "Achievements", ["trophy", "goal", "award"]),
    _I("real_estate_agent", Symbols.real_estate_agent_rounded, "Rent Income", ["rent", "property", "real estate"]),
    _I("apartment", Symbols.apartment_rounded, "Rent", ["rent", "apartment", "flat", "building"]),
    _I("villa", Symbols.villa_rounded, "Villa", ["villa", "house"]),
    _I("landscape", Symbols.landscape_rounded, "Landscape", ["landscape"]),
    _I("forest", Symbols.forest_rounded, "Forest", ["forest"]),
    _I("agriculture", Symbols.agriculture_rounded, "Agriculture", ["agriculture"]),
    _I("solar_power", Symbols.solar_power_rounded, "Solar Power", ["solar", "power"]),
    _I("oil_barrel", Symbols.oil_barrel_rounded, "Oil Barrel", ["oil", "barrel"]),
    _I("gas_meter", Symbols.gas_meter_rounded, "Gas", ["gas", "utilities"]),
    _I("area_chart", Symbols.area_chart_rounded, "Area Chart", ["area", "chart"]),
    _I("bubble_chart", Symbols.bubble_chart_rounded, "Bubble Chart", ["bubble", "chart"]),
    _I("chart_data", Symbols.chart_data_rounded, "Chart Data", ["chart", "data"]),
    _I("multiline_chart", Symbols.multiline_chart_rounded, "Multiline Chart", ["multiline", "chart"]),
    _I("ssid_chart", Symbols.ssid_chart_rounded, "Ssid Chart", ["ssid", "chart"]),
    _I("stacked_bar_chart", Symbols.stacked_bar_chart_rounded, "Stacked Bar Chart", ["stacked", "bar", "chart"]),
    _I("waterfall_chart", Symbols.waterfall_chart_rounded, "Waterfall Chart", ["waterfall", "chart"]),
    _I("pie_chart_filled", Symbols.pie_chart_filled_rounded, "Pie Chart Filled", ["pie", "chart", "filled"]),
    _I("finance_mode", Symbols.finance_mode_rounded, "Finance Mode", ["finance", "mode"]),
    _I("monitoring", Symbols.monitoring_rounded, "Monitoring", ["monitoring"]),
    _I("trending_flat", Symbols.trending_flat_rounded, "Trending Flat", ["trending", "flat"]),
    _I("warehouse", Symbols.warehouse_rounded, "Warehouse", ["warehouse"]),
    _I("business", Symbols.business_rounded, "Business", ["business"]),
    _I("add_business", Symbols.add_business_rounded, "Add Business", ["add", "business"]),
  ]),
  MaterialIconSection("income", "Income & Work", [
    _I("work", Symbols.work_rounded, "Salary", ["salary", "work", "job", "income"]),
    _I("business_center", Symbols.business_center_rounded, "Business", ["business", "work"]),
    _I("badge", Symbols.badge_rounded, "Freelance", ["freelance", "id", "work"]),
    _I("engineering", Symbols.engineering_rounded, "Engineering", ["engineering"]),
    _I("construction", Symbols.construction_rounded, "Construction", ["construction", "renovation"]),
    _I("handshake", Symbols.handshake_rounded, "Loans", ["loan", "deal", "lend", "debt"]),
    _I("volunteer_activism", Symbols.volunteer_activism_rounded, "Charity", ["charity", "donation", "zakat", "sadaqah", "give"]),
    _I("redeem", Symbols.redeem_rounded, "Gifts", ["gift", "redeem", "voucher"]),
    _I("card_giftcard", Symbols.card_giftcard_rounded, "Gift Cards", ["gift", "card", "voucher"]),
    _I("loyalty", Symbols.loyalty_rounded, "Rewards", ["loyalty", "points", "rewards"]),
    _I("percent", Symbols.percent_rounded, "Interest", ["interest", "percent", "rate"]),
    _I("arrow_downward", Symbols.arrow_downward_rounded, "Income", ["income", "in"]),
    _I("arrow_upward", Symbols.arrow_upward_rounded, "Expense", ["expense", "out"]),
    _I("celebration", Symbols.celebration_rounded, "Celebrations", ["party", "celebration", "eid"]),
    _I("storefront", Symbols.storefront_rounded, "Stores", ["store", "shop", "market"]),
    _I("store", Symbols.store_rounded, "Stores", ["store", "shop"]),
    _I("support_agent", Symbols.support_agent_rounded, "Services", ["service", "support", "helper"]),
    _I("computer", Symbols.computer_rounded, "Computer", ["computer", "laptop", "pc"]),
    _I("laptop_mac", Symbols.laptop_mac_rounded, "Laptop", ["laptop", "macbook"]),
    _I("design_services", Symbols.design_services_rounded, "Design Services", ["design", "services"]),
    _I("brush", Symbols.brush_rounded, "Brush", ["brush"]),
    _I("draw", Symbols.draw_rounded, "Draw", ["draw"]),
    _I("camera", Symbols.camera_rounded, "Camera", ["camera"]),
    _I("code", Symbols.code_rounded, "Software", ["software", "apps", "code"]),
    _I("terminal", Symbols.terminal_rounded, "Terminal", ["terminal"]),
    _I("school", Symbols.school_rounded, "Education", ["school", "education", "tuition", "fees"]),
    _I("groups", Symbols.groups_rounded, "Groups", ["groups"]),
    _I("person_add", Symbols.person_add_rounded, "Person Add", ["person", "add"]),
    _I("business_chip", Symbols.business_chip_rounded, "Business Chip", ["business", "chip"]),
    _I("team_dashboard", Symbols.team_dashboard_rounded, "Team Dashboard", ["team", "dashboard"]),
    _I("work_history", Symbols.work_history_rounded, "Work History", ["work", "history"]),
    _I("work_outline", Symbols.work_outline_rounded, "Work Outline", ["work", "outline"]),
    _I("person_celebrate", Symbols.person_celebrate_rounded, "Person Celebrate", ["person", "celebrate"]),
    _I("laptop_chromebook", Symbols.laptop_chromebook_rounded, "Laptop Chromebook", ["laptop", "chromebook"]),
  ]),
  MaterialIconSection("food", "Food & Drink", [
    _I("restaurant", Symbols.restaurant_rounded, "Dining", ["food", "restaurant", "eat", "dining"]),
    _I("restaurant_menu", Symbols.restaurant_menu_rounded, "Restaurant Menu", ["restaurant", "menu"]),
    _I("lunch_dining", Symbols.lunch_dining_rounded, "Fast Food", ["burger", "lunch", "food"]),
    _I("dinner_dining", Symbols.dinner_dining_rounded, "Dinner", ["dinner", "pasta", "food"]),
    _I("breakfast_dining", Symbols.breakfast_dining_rounded, "Breakfast", ["breakfast", "bread", "food"]),
    _I("brunch_dining", Symbols.brunch_dining_rounded, "Brunch", ["brunch", "food"]),
    _I("ramen_dining", Symbols.ramen_dining_rounded, "Asian Food", ["ramen", "noodles", "food"]),
    _I("rice_bowl", Symbols.rice_bowl_rounded, "Rice", ["rice", "bowl", "food"]),
    _I("set_meal", Symbols.set_meal_rounded, "Seafood", ["fish", "seafood", "meal"]),
    _I("kebab_dining", Symbols.kebab_dining_rounded, "Kebab", ["kebab", "shawarma", "grill"]),
    _I("local_pizza", Symbols.local_pizza_rounded, "Pizza", ["pizza", "food"]),
    _I("bakery_dining", Symbols.bakery_dining_rounded, "Bakery", ["bakery", "bread", "pastry"]),
    _I("cake", Symbols.cake_rounded, "Desserts", ["cake", "dessert", "birthday"]),
    _I("icecream", Symbols.icecream_rounded, "Ice Cream", ["ice cream", "dessert"]),
    _I("cookie", Symbols.cookie_rounded, "Snacks", ["cookie", "snack"]),
    _I("fastfood", Symbols.fastfood_rounded, "Fast Food", ["fast food", "burger", "fries"]),
    _I("takeout_dining", Symbols.takeout_dining_rounded, "Takeout", ["takeout", "delivery", "food"]),
    _I("local_cafe", Symbols.local_cafe_rounded, "Coffee", ["coffee", "cafe", "tea"]),
    _I("coffee", Symbols.coffee_rounded, "Coffee", ["coffee", "cup"]),
    _I("coffee_maker", Symbols.coffee_maker_rounded, "Coffee Maker", ["coffee", "maker"]),
    _I("emoji_food_beverage", Symbols.emoji_food_beverage_rounded, "Tea", ["tea", "karak", "drink"]),
    _I("local_bar", Symbols.local_bar_rounded, "Drinks", ["drinks", "bar", "cocktail"]),
    _I("liquor", Symbols.liquor_rounded, "Liquor", ["liquor"]),
    _I("wine_bar", Symbols.wine_bar_rounded, "Wine Bar", ["wine", "bar"]),
    _I("sports_bar", Symbols.sports_bar_rounded, "Sports Bar", ["sports", "bar"]),
    _I("local_drink", Symbols.local_drink_rounded, "Water", ["water", "drink"]),
    _I("water_bottle", Symbols.water_bottle_rounded, "Water", ["water", "bottle"]),
    _I("nutrition", Symbols.nutrition_rounded, "Fruits", ["fruit", "nutrition", "healthy"]),
    _I("egg", Symbols.egg_rounded, "Groceries", ["egg", "groceries"]),
    _I("egg_alt", Symbols.egg_alt_rounded, "Egg Alt", ["egg", "alt"]),
    _I("grocery", Symbols.grocery_rounded, "Groceries", ["grocery", "vegetables", "supermarket"]),
    _I("local_grocery_store", Symbols.local_grocery_store_rounded, "Groceries", ["grocery", "cart", "supermarket"]),
    _I("kitchen", Symbols.kitchen_rounded, "Kitchen", ["kitchen", "fridge"]),
    _I("skillet", Symbols.skillet_rounded, "Cooking", ["cooking", "pan", "kitchen"]),
    _I("outdoor_grill", Symbols.outdoor_grill_rounded, "BBQ", ["bbq", "grill"]),
    _I("soup_kitchen", Symbols.soup_kitchen_rounded, "Soup Kitchen", ["soup", "kitchen"]),
    _I("cooking", Symbols.cooking_rounded, "Cooking", ["cooking"]),
    _I("blender", Symbols.blender_rounded, "Blender", ["blender"]),
    _I("microwave", Symbols.microwave_rounded, "Microwave", ["microwave"]),
    _I("food_bank", Symbols.food_bank_rounded, "Food Bank", ["food", "bank"]),
    _I("tapas", Symbols.tapas_rounded, "Tapas", ["tapas"]),
    _I("local_dining", Symbols.local_dining_rounded, "Local Dining", ["local", "dining"]),
    _I("dining", Symbols.dining_rounded, "Dining", ["dining"]),
    _I("no_food", Symbols.no_food_rounded, "No Food", ["no", "food"]),
    _I("cake_add", Symbols.cake_add_rounded, "Cake Add", ["cake", "add"]),
    _I("bento", Symbols.bento_rounded, "Bento", ["bento"]),
    _I("flatware", Symbols.flatware_rounded, "Flatware", ["flatware"]),
    _I("hot_tub", Symbols.hot_tub_rounded, "Hot Tub", ["hot", "tub"]),
    _I("water_full", Symbols.water_full_rounded, "Water Full", ["water", "full"]),
  ]),
  MaterialIconSection("shopping", "Shopping", [
    _I("shopping_cart", Symbols.shopping_cart_rounded, "Shopping", ["shopping", "cart", "buy"]),
    _I("shopping_bag", Symbols.shopping_bag_rounded, "Shopping", ["shopping", "bag", "mall"]),
    _I("shopping_basket", Symbols.shopping_basket_rounded, "Shopping", ["basket", "shopping"]),
    _I("local_mall", Symbols.local_mall_rounded, "Mall", ["mall", "shopping"]),
    _I("local_convenience_store", Symbols.local_convenience_store_rounded, "Convenience Store", ["convenience", "store", "baqala"]),
    _I("package_2", Symbols.package_2_rounded, "Online Orders", ["package", "amazon", "noon", "parcel", "online"]),
    _I("inventory_2", Symbols.inventory_2_rounded, "Storage", ["storage", "boxes", "moving"]),
    _I("local_shipping", Symbols.local_shipping_rounded, "Shipping", ["shipping", "delivery", "truck"]),
    _I("checkroom", Symbols.checkroom_rounded, "Clothing", ["clothes", "clothing", "fashion"]),
    _I("apparel", Symbols.apparel_rounded, "Clothing", ["clothes", "shirt", "fashion"]),
    _I("styler", Symbols.styler_rounded, "Laundry", ["laundry", "dry cleaning", "clothes"]),
    _I("steps", Symbols.steps_rounded, "Shoes", ["shoes", "footwear"]),
    _I("watch", Symbols.watch_rounded, "Watches", ["watch", "accessories"]),
    _I("eyeglasses", Symbols.eyeglasses_rounded, "Glasses", ["glasses", "optical"]),
    _I("face_retouching_natural", Symbols.face_retouching_natural_rounded, "Beauty", ["beauty", "makeup", "cosmetics"]),
    _I("local_offer", Symbols.local_offer_rounded, "Local Offer", ["local", "offer"]),
    _I("new_releases", Symbols.new_releases_rounded, "New Releases", ["new", "releases"]),
    _I("shoppingmode", Symbols.shoppingmode_rounded, "Shoppingmode", ["shoppingmode"]),
    _I("deployed_code", Symbols.deployed_code_rounded, "Deployed Code", ["deployed", "code"]),
    _I("shop", Symbols.shop_rounded, "Shop", ["shop"]),
    _I("shop_2", Symbols.shop_2_rounded, "Shop 2", ["shop"]),
    _I("shopping_cart_checkout", Symbols.shopping_cart_checkout_rounded, "Shopping Cart Checkout", ["shopping", "cart", "checkout"]),
    _I("add_shopping_cart", Symbols.add_shopping_cart_rounded, "Add Shopping Cart", ["add", "shopping", "cart"]),
    _I("store_mall_directory", Symbols.store_mall_directory_rounded, "Store Mall Directory", ["store", "mall", "directory"]),
    _I("trolley", Symbols.trolley_rounded, "Trolley", ["trolley"]),
    _I("household_supplies", Symbols.household_supplies_rounded, "Household Supplies", ["household", "supplies"]),
    _I("personal_bag", Symbols.personal_bag_rounded, "Personal Bag", ["personal", "bag"]),
    _I("travel_luggage_and_bags", Symbols.travel_luggage_and_bags_rounded, "Travel Luggage And Bags", ["travel", "luggage", "and", "bags"]),
    _I("toys_and_games", Symbols.toys_and_games_rounded, "Toys And Games", ["toys", "and", "games"]),
    _I("featured_seasonal_and_gifts", Symbols.featured_seasonal_and_gifts_rounded, "Featured Seasonal And Gifts", ["featured", "seasonal", "and", "gifts"]),
    _I("garden_cart", Symbols.garden_cart_rounded, "Garden Cart", ["garden", "cart"]),
    _I("pet_supplies", Symbols.pet_supplies_rounded, "Pet Supplies", ["pet", "supplies"]),
  ]),
  MaterialIconSection("personal", "Personal Care", [
    _I("content_cut", Symbols.content_cut_rounded, "Haircut", ["haircut", "barber", "salon"]),
    _I("spa", Symbols.spa_rounded, "Spa", ["spa", "massage", "relax"]),
    _I("soap", Symbols.soap_rounded, "Toiletries", ["soap", "toiletries", "hygiene"]),
    _I("sanitizer", Symbols.sanitizer_rounded, "Personal Care", ["sanitizer", "care"]),
    _I("face", Symbols.face_rounded, "Face", ["face"]),
    _I("face_2", Symbols.face_2_rounded, "Face 2", ["face"]),
    _I("face_3", Symbols.face_3_rounded, "Face 3", ["face"]),
    _I("face_4", Symbols.face_4_rounded, "Face 4", ["face"]),
    _I("self_care", Symbols.self_care_rounded, "Self Care", ["self", "care"]),
    _I("health_and_beauty", Symbols.health_and_beauty_rounded, "Health And Beauty", ["health", "and", "beauty"]),
    _I("dry_cleaning", Symbols.dry_cleaning_rounded, "Dry Cleaning", ["dry", "cleaning"]),
    _I("local_laundry_service", Symbols.local_laundry_service_rounded, "Laundry", ["laundry", "washing"]),
    _I("wc", Symbols.wc_rounded, "Wc", ["wc"]),
    _I("bathtub", Symbols.bathtub_rounded, "Bathtub", ["bathtub"]),
    _I("shower", Symbols.shower_rounded, "Shower", ["shower"]),
    _I("clean_hands", Symbols.clean_hands_rounded, "Clean Hands", ["clean", "hands"]),
    _I("laundry", Symbols.laundry_rounded, "Laundry", ["laundry"]),
    _I("face_unlock", Symbols.face_unlock_rounded, "Face Unlock", ["face", "unlock"]),
    _I("medical_mask", Symbols.medical_mask_rounded, "Medical Mask", ["medical", "mask"]),
    _I("menstrual_health", Symbols.menstrual_health_rounded, "Menstrual Health", ["menstrual", "health"]),
  ]),
  MaterialIconSection("home", "Home & Bills", [
    _I("home", Symbols.home_rounded, "Home", ["home", "house", "rent"]),
    _I("house", Symbols.house_rounded, "House", ["house", "home"]),
    _I("cottage", Symbols.cottage_rounded, "Cottage", ["cottage"]),
    _I("key", Symbols.key_rounded, "Rent", ["key", "rent", "lease"]),
    _I("bed", Symbols.bed_rounded, "Bedroom", ["bed", "furniture"]),
    _I("weekend", Symbols.weekend_rounded, "Furniture", ["furniture", "sofa", "home"]),
    _I("chair", Symbols.chair_rounded, "Furniture", ["chair", "furniture"]),
    _I("chair_alt", Symbols.chair_alt_rounded, "Chair Alt", ["chair", "alt"]),
    _I("table_restaurant", Symbols.table_restaurant_rounded, "Table Restaurant", ["table", "restaurant"]),
    _I("light", Symbols.light_rounded, "Lighting", ["lamp", "light"]),
    _I("lightbulb", Symbols.lightbulb_rounded, "Ideas", ["idea", "lightbulb"]),
    _I("bolt", Symbols.bolt_rounded, "Electricity", ["electricity", "power", "dewa", "utilities"]),
    _I("electric_bolt", Symbols.electric_bolt_rounded, "Electricity", ["electricity", "power"]),
    _I("water_drop", Symbols.water_drop_rounded, "Water Bill", ["water", "utilities"]),
    _I("propane_tank", Symbols.propane_tank_rounded, "Gas Cylinder", ["gas", "cylinder", "cooking"]),
    _I("ac_unit", Symbols.ac_unit_rounded, "Cooling", ["ac", "cooling", "empower", "chiller"]),
    _I("heat", Symbols.heat_rounded, "Heating", ["heating"]),
    _I("mode_fan", Symbols.mode_fan_rounded, "Mode Fan", ["mode", "fan"]),
    _I("air", Symbols.air_rounded, "Air", ["air"]),
    _I("thermostat", Symbols.thermostat_rounded, "Thermostat", ["thermostat"]),
    _I("wifi", Symbols.wifi_rounded, "Internet", ["internet", "wifi", "broadband"]),
    _I("router", Symbols.router_rounded, "Internet", ["router", "internet"]),
    _I("smartphone", Symbols.smartphone_rounded, "Phone", ["phone", "mobile", "du", "etisalat", "e&"]),
    _I("phone_in_talk", Symbols.phone_in_talk_rounded, "Phone Bill", ["phone", "call"]),
    _I("sim_card", Symbols.sim_card_rounded, "Mobile Plan", ["sim", "mobile", "recharge"]),
    _I("tv", Symbols.tv_rounded, "TV", ["tv", "television"]),
    _I("live_tv", Symbols.live_tv_rounded, "Streaming", ["streaming", "netflix", "tv"]),
    _I("subscriptions", Symbols.subscriptions_rounded, "Subscriptions", ["subscriptions", "streaming"]),
    _I("autorenew", Symbols.autorenew_rounded, "Recurring", ["recurring", "renew", "subscription"]),
    _I("cloud", Symbols.cloud_rounded, "Cloud Storage", ["cloud", "storage", "icloud", "google one"]),
    _I("mail", Symbols.mail_rounded, "Post", ["mail", "post", "letter"]),
    _I("security", Symbols.security_rounded, "Security", ["security", "alarm"]),
    _I("sensor_door", Symbols.sensor_door_rounded, "Sensor Door", ["sensor", "door"]),
    _I("doorbell", Symbols.doorbell_rounded, "Doorbell", ["doorbell"]),
    _I("handyman", Symbols.handyman_rounded, "Repairs", ["repair", "tools", "maintenance"]),
    _I("plumbing", Symbols.plumbing_rounded, "Plumbing", ["plumbing", "repair"]),
    _I("format_paint", Symbols.format_paint_rounded, "Painting", ["paint", "decor"]),
    _I("cleaning_services", Symbols.cleaning_services_rounded, "Cleaning", ["cleaning", "maid", "housekeeping"]),
    _I("mop", Symbols.mop_rounded, "Cleaning", ["mop", "cleaning"]),
    _I("yard", Symbols.yard_rounded, "Garden", ["garden", "plants", "yard"]),
    _I("potted_plant", Symbols.potted_plant_rounded, "Plants", ["plant", "garden"]),
    _I("local_florist", Symbols.local_florist_rounded, "Flowers", ["flowers", "florist"]),
    _I("grass", Symbols.grass_rounded, "Grass", ["grass"]),
    _I("roofing", Symbols.roofing_rounded, "Roofing", ["roofing"]),
    _I("garage", Symbols.garage_rounded, "Garage", ["garage"]),
    _I("fence", Symbols.fence_rounded, "Fence", ["fence"]),
    _I("dishwasher_gen", Symbols.dishwasher_gen_rounded, "Dishwasher Gen", ["dishwasher", "gen"]),
    _I("family_home", Symbols.family_home_rounded, "Family Home", ["family", "home"]),
    _I("house_siding", Symbols.house_siding_rounded, "House Siding", ["house", "siding"]),
    _I("house_with_shield", Symbols.house_with_shield_rounded, "House With Shield", ["house", "with", "shield"]),
    _I("home_repair_service", Symbols.home_repair_service_rounded, "Home Repair Service", ["home", "repair", "service"]),
    _I("home_improvement_and_tools", Symbols.home_improvement_and_tools_rounded, "Home Improvement And Tools", ["home", "improvement", "and", "tools"]),
    _I("home_and_garden", Symbols.home_and_garden_rounded, "Home And Garden", ["home", "and", "garden"]),
    _I("home_storage", Symbols.home_storage_rounded, "Home Storage", ["home", "storage"]),
    _I("home_work", Symbols.home_work_rounded, "Home Work", ["home", "work"]),
    _I("other_houses", Symbols.other_houses_rounded, "Other Houses", ["other", "houses"]),
    _I("bedroom_baby", Symbols.bedroom_baby_rounded, "Bedroom Baby", ["bedroom", "baby"]),
    _I("bedroom_child", Symbols.bedroom_child_rounded, "Bedroom Child", ["bedroom", "child"]),
    _I("bedroom_parent", Symbols.bedroom_parent_rounded, "Bedroom Parent", ["bedroom", "parent"]),
    _I("single_bed", Symbols.single_bed_rounded, "Single Bed", ["single", "bed"]),
    _I("table_bar", Symbols.table_bar_rounded, "Table Bar", ["table", "bar"]),
    _I("electric_meter", Symbols.electric_meter_rounded, "Electric Meter", ["electric", "meter"]),
    _I("electrical_services", Symbols.electrical_services_rounded, "Electrical Services", ["electrical", "services"]),
    _I("water_heater", Symbols.water_heater_rounded, "Water Heater", ["water", "heater"]),
    _I("water_damage", Symbols.water_damage_rounded, "Water Damage", ["water", "damage"]),
    _I("water_pump", Symbols.water_pump_rounded, "Water Pump", ["water", "pump"]),
    _I("cleaning", Symbols.cleaning_rounded, "Cleaning", ["cleaning"]),
    _I("cleaning_bucket", Symbols.cleaning_bucket_rounded, "Cleaning Bucket", ["cleaning", "bucket"]),
    _I("carpenter", Symbols.carpenter_rounded, "Carpenter", ["carpenter"]),
    _I("tools_power_drill", Symbols.tools_power_drill_rounded, "Tools Power Drill", ["tools", "power", "drill"]),
    _I("tools_wrench", Symbols.tools_wrench_rounded, "Tools Wrench", ["tools", "wrench"]),
    _I("tools_ladder", Symbols.tools_ladder_rounded, "Tools Ladder", ["tools", "ladder"]),
    _I("service_toolbox", Symbols.service_toolbox_rounded, "Service Toolbox", ["service", "toolbox"]),
    _I("outdoor_garden", Symbols.outdoor_garden_rounded, "Outdoor Garden", ["outdoor", "garden"]),
    _I("nightlight", Symbols.nightlight_rounded, "Nightlight", ["nightlight"]),
    _I("light_mode", Symbols.light_mode_rounded, "Light Mode", ["light", "mode"]),
    _I("thermostat_carbon", Symbols.thermostat_carbon_rounded, "Thermostat Carbon", ["thermostat", "carbon"]),
    _I("energy_savings_leaf", Symbols.energy_savings_leaf_rounded, "Energy Savings Leaf", ["energy", "savings", "leaf"]),
    _I("wifi_home", Symbols.wifi_home_rounded, "Wifi Home", ["wifi", "home"]),
    _I("tv_remote", Symbols.tv_remote_rounded, "Tv Remote", ["tv", "remote"]),
    _I("connected_tv", Symbols.connected_tv_rounded, "Connected Tv", ["connected", "tv"]),
    _I("home_speaker", Symbols.home_speaker_rounded, "Home Speaker", ["home", "speaker"]),
    _I("light_group", Symbols.light_group_rounded, "Light Group", ["light", "group"]),
    _I("local_phone", Symbols.local_phone_rounded, "Local Phone", ["local", "phone"]),
    _I("deskphone", Symbols.deskphone_rounded, "Deskphone", ["deskphone"]),
    _I("mark_email_unread", Symbols.mark_email_unread_rounded, "Mark Email Unread", ["mark", "email", "unread"]),
    _I("markunread_mailbox", Symbols.markunread_mailbox_rounded, "Markunread Mailbox", ["markunread", "mailbox"]),
    _I("key_vertical", Symbols.key_vertical_rounded, "Key Vertical", ["key", "vertical"]),
  ]),
  MaterialIconSection("transport", "Transport", [
    _I("directions_car", Symbols.directions_car_rounded, "Car", ["car", "vehicle", "auto"]),
    _I("local_gas_station", Symbols.local_gas_station_rounded, "Fuel", ["fuel", "petrol", "gas", "adnoc", "enoc"]),
    _I("ev_station", Symbols.ev_station_rounded, "EV Charging", ["ev", "charging", "electric car"]),
    _I("local_parking", Symbols.local_parking_rounded, "Parking", ["parking", "rta"]),
    _I("local_taxi", Symbols.local_taxi_rounded, "Taxi", ["taxi", "cab", "uber", "careem"]),
    _I("hail", Symbols.hail_rounded, "Ride Hailing", ["ride", "uber", "careem", "hail"]),
    _I("car_repair", Symbols.car_repair_rounded, "Car Service", ["car", "service", "repair", "garage"]),
    _I("local_car_wash", Symbols.local_car_wash_rounded, "Car Wash", ["car wash", "cleaning"]),
    _I("tire_repair", Symbols.tire_repair_rounded, "Tyres", ["tyre", "tire", "repair"]),
    _I("car_rental", Symbols.car_rental_rounded, "Car Rental", ["rental", "car", "lease"]),
    _I("car_crash", Symbols.car_crash_rounded, "Car Insurance", ["insurance", "accident", "car"]),
    _I("traffic", Symbols.traffic_rounded, "Traffic Fines", ["traffic", "fine", "salik"]),
    _I("two_wheeler", Symbols.two_wheeler_rounded, "Motorbike", ["motorbike", "scooter", "bike"]),
    _I("pedal_bike", Symbols.pedal_bike_rounded, "Bicycle", ["bicycle", "bike", "cycling"]),
    _I("electric_scooter", Symbols.electric_scooter_rounded, "Scooter", ["scooter", "e-scooter"]),
    _I("scooter", Symbols.scooter_rounded, "Food Delivery", ["delivery", "talabat", "deliveroo", "scooter"]),
    _I("directions_bus", Symbols.directions_bus_rounded, "Bus", ["bus", "transport", "nol"]),
    _I("train", Symbols.train_rounded, "Train", ["train", "railway"]),
    _I("subway", Symbols.subway_rounded, "Metro", ["metro", "subway", "nol"]),
    _I("tram", Symbols.tram_rounded, "Tram", ["tram", "transport"]),
    _I("directions_boat", Symbols.directions_boat_rounded, "Boat", ["boat", "ferry", "abra"]),
    _I("commute", Symbols.commute_rounded, "Commute", ["commute", "transport"]),
    _I("airport_shuttle", Symbols.airport_shuttle_rounded, "Airport Shuttle", ["airport", "shuttle"]),
    _I("electric_car", Symbols.electric_car_rounded, "Electric Car", ["electric", "car"]),
    _I("electric_bike", Symbols.electric_bike_rounded, "Electric Bike", ["electric", "bike"]),
    _I("directions_walk", Symbols.directions_walk_rounded, "Directions Walk", ["directions", "walk"]),
    _I("directions_run", Symbols.directions_run_rounded, "Running", ["running", "sport"]),
    _I("garage_home", Symbols.garage_home_rounded, "Garage Home", ["garage", "home"]),
    _I("minor_crash", Symbols.minor_crash_rounded, "Minor Crash", ["minor", "crash"]),
    _I("directions_car_filled", Symbols.directions_car_filled_rounded, "Directions Car Filled", ["directions", "car", "filled"]),
    _I("directions_bus_filled", Symbols.directions_bus_filled_rounded, "Directions Bus Filled", ["directions", "bus", "filled"]),
    _I("directions_boat_filled", Symbols.directions_boat_filled_rounded, "Directions Boat Filled", ["directions", "boat", "filled"]),
    _I("directions_bike", Symbols.directions_bike_rounded, "Directions Bike", ["directions", "bike"]),
    _I("electric_moped", Symbols.electric_moped_rounded, "Electric Moped", ["electric", "moped"]),
    _I("electric_rickshaw", Symbols.electric_rickshaw_rounded, "Electric Rickshaw", ["electric", "rickshaw"]),
    _I("bike_scooter", Symbols.bike_scooter_rounded, "Bike Scooter", ["bike", "scooter"]),
    _I("car_tag", Symbols.car_tag_rounded, "Car Tag", ["car", "tag"]),
    _I("taxi_alert", Symbols.taxi_alert_rounded, "Taxi Alert", ["taxi", "alert"]),
    _I("speed_camera", Symbols.speed_camera_rounded, "Speed Camera", ["speed", "camera"]),
    _I("emoji_transportation", Symbols.emoji_transportation_rounded, "Emoji Transportation", ["emoji", "transportation"]),
    _I("transportation", Symbols.transportation_rounded, "Transportation", ["transportation"]),
    _I("cable_car", Symbols.cable_car_rounded, "Cable Car", ["cable", "car"]),
    _I("trolley_cable_car", Symbols.trolley_cable_car_rounded, "Trolley Cable Car", ["trolley", "cable", "car"]),
    _I("mode_of_travel", Symbols.mode_of_travel_rounded, "Mode Of Travel", ["mode", "of", "travel"]),
  ]),
  MaterialIconSection("travel", "Travel", [
    _I("flight", Symbols.flight_rounded, "Flights", ["flight", "plane", "airline", "travel"]),
    _I("flight_takeoff", Symbols.flight_takeoff_rounded, "Flights", ["flight", "takeoff", "travel"]),
    _I("flight_land", Symbols.flight_land_rounded, "Flight Land", ["flight", "land"]),
    _I("luggage", Symbols.luggage_rounded, "Travel", ["luggage", "travel", "trip"]),
    _I("hotel", Symbols.hotel_rounded, "Hotels", ["hotel", "stay", "accommodation"]),
    _I("king_bed", Symbols.king_bed_rounded, "Accommodation", ["hotel", "airbnb", "stay"]),
    _I("beach_access", Symbols.beach_access_rounded, "Holidays", ["holiday", "vacation", "beach"]),
    _I("travel_explore", Symbols.travel_explore_rounded, "Travel", ["travel", "explore"]),
    _I("map", Symbols.map_rounded, "Trips", ["map", "trip", "tour"]),
    _I("tour", Symbols.tour_rounded, "Tours", ["tour", "sightseeing"]),
    _I("id_card", Symbols.id_card_rounded, "Visa & ID", ["visa", "passport", "id", "emirates id"]),
    _I("public", Symbols.public_rounded, "Abroad", ["abroad", "world", "international"]),
    _I("location_on", Symbols.location_on_rounded, "Location On", ["location", "on"]),
    _I("explore", Symbols.explore_rounded, "Explore", ["explore"]),
    _I("houseboat", Symbols.houseboat_rounded, "Houseboat", ["houseboat"]),
    _I("cabin", Symbols.cabin_rounded, "Cabin", ["cabin"]),
    _I("camping", Symbols.camping_rounded, "Camping", ["camping", "tent", "desert"]),
    _I("holiday_village", Symbols.holiday_village_rounded, "Holiday Village", ["holiday", "village"]),
    _I("pool", Symbols.pool_rounded, "Swimming", ["pool", "swimming"]),
    _I("attractions", Symbols.attractions_rounded, "Theme Parks", ["theme park", "rides"]),
    _I("sailing", Symbols.sailing_rounded, "Sailing", ["sailing", "yacht"]),
    _I("mosque", Symbols.mosque_rounded, "Mosque", ["mosque", "masjid", "religion"]),
    _I("church", Symbols.church_rounded, "Church", ["church", "religion"]),
    _I("temple_hindu", Symbols.temple_hindu_rounded, "Temple", ["temple", "religion"]),
    _I("synagogue", Symbols.synagogue_rounded, "Synagogue", ["synagogue", "religion"]),
    _I("temple_buddhist", Symbols.temple_buddhist_rounded, "Temple Buddhist", ["temple", "buddhist"]),
    _I("airplane_ticket", Symbols.airplane_ticket_rounded, "Airplane Ticket", ["airplane", "ticket"]),
    _I("flights_and_hotels", Symbols.flights_and_hotels_rounded, "Flights And Hotels", ["flights", "and", "hotels"]),
    _I("flight_class", Symbols.flight_class_rounded, "Flight Class", ["flight", "class"]),
    _I("card_travel", Symbols.card_travel_rounded, "Card Travel", ["card", "travel"]),
    _I("carry_on_bag", Symbols.carry_on_bag_rounded, "Carry On Bag", ["carry", "on", "bag"]),
    _I("checked_bag", Symbols.checked_bag_rounded, "Checked Bag", ["checked", "bag"]),
    _I("travel", Symbols.travel_rounded, "Travel", ["travel"]),
    _I("local_hotel", Symbols.local_hotel_rounded, "Local Hotel", ["local", "hotel"]),
    _I("hotel_class", Symbols.hotel_class_rounded, "Hotel Class", ["hotel", "class"]),
    _I("location_home", Symbols.location_home_rounded, "Location Home", ["location", "home"]),
    _I("streetview", Symbols.streetview_rounded, "Streetview", ["streetview"]),
  ]),
  MaterialIconSection("health", "Health & Fitness", [
    _I("medical_services", Symbols.medical_services_rounded, "Medical", ["medical", "doctor", "health"]),
    _I("local_hospital", Symbols.local_hospital_rounded, "Hospital", ["hospital", "health"]),
    _I("stethoscope", Symbols.stethoscope_rounded, "Doctor", ["doctor", "clinic", "checkup"]),
    _I("medication", Symbols.medication_rounded, "Pharmacy", ["pharmacy", "medicine", "drugs"]),
    _I("local_pharmacy", Symbols.local_pharmacy_rounded, "Pharmacy", ["pharmacy", "chemist"]),
    _I("vaccines", Symbols.vaccines_rounded, "Vaccines", ["vaccine", "injection"]),
    _I("dentistry", Symbols.dentistry_rounded, "Dentist", ["dentist", "teeth"]),
    _I("visibility", Symbols.visibility_rounded, "Eye Care", ["eye", "optician"]),
    _I("psychology", Symbols.psychology_rounded, "Therapy", ["therapy", "mental health"]),
    _I("favorite", Symbols.favorite_rounded, "Health", ["health", "heart", "love"]),
    _I("monitor_heart", Symbols.monitor_heart_rounded, "Health", ["heart", "health"]),
    _I("healing", Symbols.healing_rounded, "Healing", ["healing"]),
    _I("emergency", Symbols.emergency_rounded, "Emergency Fund", ["emergency", "fund"]),
    _I("health_and_safety", Symbols.health_and_safety_rounded, "Insurance", ["insurance", "health", "safety"]),
    _I("ecg_heart", Symbols.ecg_heart_rounded, "Ecg Heart", ["ecg", "heart"]),
    _I("glucose", Symbols.glucose_rounded, "Glucose", ["glucose"]),
    _I("blood_pressure", Symbols.blood_pressure_rounded, "Blood Pressure", ["blood", "pressure"]),
    _I("pill", Symbols.pill_rounded, "Pill", ["pill"]),
    _I("fitness_center", Symbols.fitness_center_rounded, "Gym", ["gym", "fitness", "workout"]),
    _I("exercise", Symbols.exercise_rounded, "Fitness", ["exercise", "fitness"]),
    _I("sports_gymnastics", Symbols.sports_gymnastics_rounded, "Yoga", ["yoga", "gymnastics"]),
    _I("self_improvement", Symbols.self_improvement_rounded, "Wellness", ["meditation", "wellness"]),
    _I("sports_soccer", Symbols.sports_soccer_rounded, "Football", ["football", "soccer", "sport"]),
    _I("sports_tennis", Symbols.sports_tennis_rounded, "Tennis", ["tennis", "padel", "sport"]),
    _I("sports_cricket", Symbols.sports_cricket_rounded, "Cricket", ["cricket", "sport"]),
    _I("sports_basketball", Symbols.sports_basketball_rounded, "Basketball", ["basketball", "sport"]),
    _I("golf_course", Symbols.golf_course_rounded, "Golf", ["golf", "sport"]),
    _I("hiking", Symbols.hiking_rounded, "Hiking", ["hiking", "outdoors"]),
    _I("sports_martial_arts", Symbols.sports_martial_arts_rounded, "Martial Arts", ["martial arts", "karate"]),
    _I("sports_football", Symbols.sports_football_rounded, "Sports Football", ["sports", "football"]),
    _I("sports_volleyball", Symbols.sports_volleyball_rounded, "Sports Volleyball", ["sports", "volleyball"]),
    _I("sports_handball", Symbols.sports_handball_rounded, "Sports Handball", ["sports", "handball"]),
    _I("rowing", Symbols.rowing_rounded, "Rowing", ["rowing"]),
    _I("surfing", Symbols.surfing_rounded, "Surfing", ["surfing"]),
    _I("skateboarding", Symbols.skateboarding_rounded, "Skateboarding", ["skateboarding"]),
    _I("snowboarding", Symbols.snowboarding_rounded, "Snowboarding", ["snowboarding"]),
    _I("downhill_skiing", Symbols.downhill_skiing_rounded, "Downhill Skiing", ["downhill", "skiing"]),
    _I("medical_information", Symbols.medical_information_rounded, "Medical Information", ["medical", "information"]),
    _I("home_health", Symbols.home_health_rounded, "Home Health", ["home", "health"]),
    _I("health_metrics", Symbols.health_metrics_rounded, "Health Metrics", ["health", "metrics"]),
    _I("cardiology", Symbols.cardiology_rounded, "Cardiology", ["cardiology"]),
    _I("gastroenterology", Symbols.gastroenterology_rounded, "Gastroenterology", ["gastroenterology"]),
    _I("fitness_tracker", Symbols.fitness_tracker_rounded, "Fitness Tracker", ["fitness", "tracker"]),
    _I("wheelchair_pickup", Symbols.wheelchair_pickup_rounded, "Wheelchair Pickup", ["wheelchair", "pickup"]),
    _I("sports", Symbols.sports_rounded, "Sports", ["sports"]),
    _I("sports_baseball", Symbols.sports_baseball_rounded, "Sports Baseball", ["sports", "baseball"]),
    _I("sports_golf", Symbols.sports_golf_rounded, "Sports Golf", ["sports", "golf"]),
    _I("sports_hockey", Symbols.sports_hockey_rounded, "Sports Hockey", ["sports", "hockey"]),
    _I("sports_mma", Symbols.sports_mma_rounded, "Sports Mma", ["sports", "mma"]),
    _I("sports_motorsports", Symbols.sports_motorsports_rounded, "Sports Motorsports", ["sports", "motorsports"]),
    _I("sports_rugby", Symbols.sports_rugby_rounded, "Sports Rugby", ["sports", "rugby"]),
    _I("sports_kabaddi", Symbols.sports_kabaddi_rounded, "Sports Kabaddi", ["sports", "kabaddi"]),
    _I("sports_score", Symbols.sports_score_rounded, "Sports Score", ["sports", "score"]),
    _I("run_circle", Symbols.run_circle_rounded, "Run Circle", ["run", "circle"]),
    _I("barefoot", Symbols.barefoot_rounded, "Barefoot", ["barefoot"]),
  ]),
  MaterialIconSection("fun", "Entertainment", [
    _I("movie", Symbols.movie_rounded, "Movies", ["movie", "cinema", "film"]),
    _I("theaters", Symbols.theaters_rounded, "Cinema", ["cinema", "theater"]),
    _I("confirmation_number", Symbols.confirmation_number_rounded, "Tickets", ["tickets", "events"]),
    _I("local_activity", Symbols.local_activity_rounded, "Activities", ["activity", "tickets"]),
    _I("festival", Symbols.festival_rounded, "Events", ["festival", "event"]),
    _I("music_note", Symbols.music_note_rounded, "Music", ["music", "spotify", "anghami"]),
    _I("headphones", Symbols.headphones_rounded, "Audio", ["headphones", "audio"]),
    _I("podcasts", Symbols.podcasts_rounded, "Podcasts", ["podcast"]),
    _I("sports_esports", Symbols.sports_esports_rounded, "Gaming", ["gaming", "games", "playstation", "xbox"]),
    _I("stadia_controller", Symbols.stadia_controller_rounded, "Games", ["games", "controller"]),
    _I("casino", Symbols.casino_rounded, "Games", ["dice", "board games"]),
    _I("extension", Symbols.extension_rounded, "Hobbies", ["hobby", "puzzle"]),
    _I("palette", Symbols.palette_rounded, "Art", ["art", "painting", "hobby"]),
    _I("photo_camera", Symbols.photo_camera_rounded, "Photography", ["camera", "photography"]),
    _I("piano", Symbols.piano_rounded, "Instruments", ["piano", "music"]),
    _I("menu_book", Symbols.menu_book_rounded, "Books", ["books", "reading"]),
    _I("auto_stories", Symbols.auto_stories_rounded, "Books", ["books", "stories"]),
    _I("newspaper", Symbols.newspaper_rounded, "News", ["news", "newspaper", "magazine"]),
    _I("park", Symbols.park_rounded, "Outdoors", ["park", "outdoors"]),
    _I("kayaking", Symbols.kayaking_rounded, "Water Sports", ["kayak", "water sports"]),
    _I("scuba_diving", Symbols.scuba_diving_rounded, "Diving", ["diving", "scuba"]),
    _I("nightlife", Symbols.nightlife_rounded, "Nightlife", ["nightlife", "club"]),
    _I("theater_comedy", Symbols.theater_comedy_rounded, "Theater Comedy", ["theater", "comedy"]),
    _I("mic", Symbols.mic_rounded, "Mic", ["mic"]),
    _I("radio", Symbols.radio_rounded, "Radio", ["radio"]),
    _I("album", Symbols.album_rounded, "Album", ["album"]),
    _I("videogame_asset", Symbols.videogame_asset_rounded, "Consoles", ["console", "gaming"]),
    _I("toys", Symbols.toys_rounded, "Toys", ["toys", "kids"]),
    _I("local_movies", Symbols.local_movies_rounded, "Local Movies", ["local", "movies"]),
    _I("movie_creation", Symbols.movie_creation_rounded, "Movie Creation", ["movie", "creation"]),
    _I("play_music", Symbols.play_music_rounded, "Play Music", ["play", "music"]),
    _I("library_music", Symbols.library_music_rounded, "Library Music", ["library", "music"]),
    _I("queue_music", Symbols.queue_music_rounded, "Queue Music", ["queue", "music"]),
    _I("music_video", Symbols.music_video_rounded, "Music Video", ["music", "video"]),
    _I("playing_cards", Symbols.playing_cards_rounded, "Playing Cards", ["playing", "cards"]),
    _I("games", Symbols.games_rounded, "Games", ["games"]),
    _I("gamepad", Symbols.gamepad_rounded, "Gamepad", ["gamepad"]),
    _I("party_mode", Symbols.party_mode_rounded, "Party Mode", ["party", "mode"]),
    _I("event_seat", Symbols.event_seat_rounded, "Event Seat", ["event", "seat"]),
    _I("tv_guide", Symbols.tv_guide_rounded, "Tv Guide", ["tv", "guide"]),
  ]),
  MaterialIconSection("family", "Family & Pets", [
    _I("family_restroom", Symbols.family_restroom_rounded, "Family", ["family", "kids"]),
    _I("child_care", Symbols.child_care_rounded, "Childcare", ["child", "baby", "nanny"]),
    _I("child_friendly", Symbols.child_friendly_rounded, "Baby", ["baby", "stroller"]),
    _I("elderly", Symbols.elderly_rounded, "Parents", ["parents", "elderly", "family"]),
    _I("diversity_3", Symbols.diversity_3_rounded, "Friends", ["friends", "people", "social"]),
    _I("group", Symbols.group_rounded, "Shared", ["group", "shared", "split"]),
    _I("person", Symbols.person_rounded, "Personal", ["personal", "person", "me"]),
    _I("pets", Symbols.pets_rounded, "Pets", ["pets", "dog", "cat"]),
    _I("cruelty_free", Symbols.cruelty_free_rounded, "Pets", ["pets", "rabbit"]),
    _I("baby_changing_station", Symbols.baby_changing_station_rounded, "Baby Changing Station", ["baby", "changing", "station"]),
    _I("stroller", Symbols.stroller_rounded, "Stroller", ["stroller"]),
    _I("crib", Symbols.crib_rounded, "Crib", ["crib"]),
    _I("backpack", Symbols.backpack_rounded, "School Supplies", ["school", "backpack"]),
    _I("account_child", Symbols.account_child_rounded, "Account Child", ["account", "child"]),
  ]),
  MaterialIconSection("education", "Education", [
    _I("library_books", Symbols.library_books_rounded, "Courses", ["courses", "books", "study"]),
    _I("history_edu", Symbols.history_edu_rounded, "University", ["university", "degree"]),
    _I("science", Symbols.science_rounded, "Science", ["science", "lab"]),
    _I("translate", Symbols.translate_rounded, "Languages", ["language", "course"]),
    _I("edit", Symbols.edit_rounded, "Stationery", ["stationery", "pen"]),
    _I("print", Symbols.print_rounded, "Printing", ["print", "office"]),
    _I("calculate", Symbols.calculate_rounded, "Calculate", ["calculate"]),
    _I("book", Symbols.book_rounded, "Book", ["book"]),
    _I("book_2", Symbols.book_2_rounded, "Book 2", ["book"]),
    _I("cast_for_education", Symbols.cast_for_education_rounded, "Cast For Education", ["cast", "for", "education"]),
    _I("co_present", Symbols.co_present_rounded, "Co Present", ["co", "present"]),
    _I("quiz", Symbols.quiz_rounded, "Quiz", ["quiz"]),
    _I("book_3", Symbols.book_3_rounded, "Book 3", ["book"]),
    _I("book_4", Symbols.book_4_rounded, "Book 4", ["book"]),
    _I("book_5", Symbols.book_5_rounded, "Book 5", ["book"]),
    _I("book_online", Symbols.book_online_rounded, "Book Online", ["book", "online"]),
    _I("collections_bookmark", Symbols.collections_bookmark_rounded, "Collections Bookmark", ["collections", "bookmark"]),
    _I("local_printshop", Symbols.local_printshop_rounded, "Local Printshop", ["local", "printshop"]),
    _I("person_book", Symbols.person_book_rounded, "Person Book", ["person", "book"]),
    _I("model_training", Symbols.model_training_rounded, "Model Training", ["model", "training"]),
  ]),
  MaterialIconSection("tech", "Tech & Subscriptions", [
    _I("devices", Symbols.devices_rounded, "Electronics", ["devices", "electronics", "gadgets"]),
    _I("tablet_mac", Symbols.tablet_mac_rounded, "Tablet", ["tablet", "ipad"]),
    _I("watch_screentime", Symbols.watch_screentime_rounded, "Smartwatch", ["smartwatch", "watch"]),
    _I("keyboard", Symbols.keyboard_rounded, "Accessories", ["keyboard", "accessories"]),
    _I("mouse", Symbols.mouse_rounded, "Accessories", ["mouse", "accessories"]),
    _I("headset_mic", Symbols.headset_mic_rounded, "Headset", ["headset", "audio"]),
    _I("speaker", Symbols.speaker_rounded, "Speakers", ["speaker", "audio"]),
    _I("memory", Symbols.memory_rounded, "Hardware", ["hardware", "chip"]),
    _I("battery_charging_full", Symbols.battery_charging_full_rounded, "Chargers", ["charger", "battery"]),
    _I("cable", Symbols.cable_rounded, "Cables", ["cable", "accessories"]),
    _I("apps", Symbols.apps_rounded, "Apps", ["apps", "app store", "play store"]),
    _I("domain", Symbols.domain_rounded, "Domains & Hosting", ["domain", "hosting", "website"]),
    _I("smart_toy", Symbols.smart_toy_rounded, "AI Tools", ["ai", "bot", "chatgpt", "claude"]),
    _I("storage", Symbols.storage_rounded, "Storage", ["storage"]),
    _I("dns", Symbols.dns_rounded, "Dns", ["dns"]),
    _I("phone_iphone", Symbols.phone_iphone_rounded, "Phone Iphone", ["phone", "iphone"]),
    _I("tv_gen", Symbols.tv_gen_rounded, "Tv Gen", ["tv", "gen"]),
    _I("laptop", Symbols.laptop_rounded, "Laptop", ["laptop"]),
    _I("laptop_windows", Symbols.laptop_windows_rounded, "Laptop Windows", ["laptop", "windows"]),
    _I("phone_android", Symbols.phone_android_rounded, "Phone Android", ["phone", "android"]),
    _I("phone", Symbols.phone_rounded, "Phone", ["phone"]),
    _I("smartphone_camera", Symbols.smartphone_camera_rounded, "Smartphone Camera", ["smartphone", "camera"]),
    _I("tablet_camera", Symbols.tablet_camera_rounded, "Tablet Camera", ["tablet", "camera"]),
    _I("camera_alt", Symbols.camera_alt_rounded, "Camera Alt", ["camera", "alt"]),
    _I("video_camera_back", Symbols.video_camera_back_rounded, "Video Camera Back", ["video", "camera", "back"]),
    _I("sd_card", Symbols.sd_card_rounded, "Sd Card", ["sd", "card"]),
    _I("security_key", Symbols.security_key_rounded, "Security Key", ["security", "key"]),
    _I("vpn_key", Symbols.vpn_key_rounded, "Vpn Key", ["vpn", "key"]),
    _I("passkey", Symbols.passkey_rounded, "Passkey", ["passkey"]),
    _I("cloud_sync", Symbols.cloud_sync_rounded, "Cloud Sync", ["cloud", "sync"]),
    _I("cloud_done", Symbols.cloud_done_rounded, "Cloud Done", ["cloud", "done"]),
    _I("wifi_password", Symbols.wifi_password_rounded, "Wifi Password", ["wifi", "password"]),
    _I("email", Symbols.email_rounded, "Email", ["email"]),
    _I("alternate_email", Symbols.alternate_email_rounded, "Alternate Email", ["alternate", "email"]),
  ]),
  MaterialIconSection("other", "Other", [
    _I("category", Symbols.category_rounded, "General", ["general", "other", "misc"]),
    _I("more_horiz", Symbols.more_horiz_rounded, "Other", ["other", "misc"]),
    _I("help", Symbols.help_rounded, "Unknown", ["unknown", "question"]),
    _I("star", Symbols.star_rounded, "Favourites", ["star", "favourite"]),
    _I("bookmark", Symbols.bookmark_rounded, "Saved", ["bookmark", "saved"]),
    _I("label", Symbols.label_rounded, "Tag", ["label", "tag"]),
    _I("flag", Symbols.flag_rounded, "Goals", ["goal", "flag", "target"]),
    _I("rocket_launch", Symbols.rocket_launch_rounded, "Projects", ["rocket", "project", "startup"]),
    _I("event", Symbols.event_rounded, "Events", ["event", "calendar"]),
    _I("calendar_month", Symbols.calendar_month_rounded, "Monthly", ["monthly", "calendar"]),
    _I("schedule", Symbols.schedule_rounded, "Time", ["time", "clock"]),
    _I("alarm", Symbols.alarm_rounded, "Reminders", ["alarm", "reminder"]),
    _I("warning", Symbols.warning_rounded, "Emergency", ["emergency", "warning"]),
    _I("smoking_rooms", Symbols.smoking_rooms_rounded, "Smoking", ["smoking", "cigarettes", "shisha"]),
    _I("local_post_office", Symbols.local_post_office_rounded, "Post Office", ["post", "courier"]),
    _I("moving", Symbols.moving_rounded, "Moving", ["moving", "relocation"]),
    _I("description", Symbols.description_rounded, "Documents", ["documents", "paperwork", "fees"]),
    _I("assignment", Symbols.assignment_rounded, "Government Fees", ["government", "fees", "typing", "amer"]),
    _I("account_box", Symbols.account_box_rounded, "Account", ["account", "profile"]),
    _I("folder", Symbols.folder_rounded, "Group", ["folder", "group"]),
    _I("folder_copy", Symbols.folder_copy_rounded, "Groups", ["folder", "groups"]),
    _I("gavel", Symbols.gavel_rounded, "Legal", ["legal", "lawyer", "court", "fine"]),
    _I("balance", Symbols.balance_rounded, "Tax", ["tax", "balance", "law"]),
    _I("policy", Symbols.policy_rounded, "Insurance", ["insurance", "policy"]),
    _I("shield", Symbols.shield_rounded, "Protection", ["insurance", "shield"]),
    _I("verified", Symbols.verified_rounded, "Verified", ["verified"]),
    _I("lock", Symbols.lock_rounded, "Lock", ["lock"]),
    _I("calendar_today", Symbols.calendar_today_rounded, "Calendar Today", ["calendar", "today"]),
    _I("event_repeat", Symbols.event_repeat_rounded, "Event Repeat", ["event", "repeat"]),
    _I("event_upcoming", Symbols.event_upcoming_rounded, "Event Upcoming", ["event", "upcoming"]),
    _I("event_available", Symbols.event_available_rounded, "Event Available", ["event", "available"]),
    _I("edit_calendar", Symbols.edit_calendar_rounded, "Edit Calendar", ["edit", "calendar"]),
    _I("punch_clock", Symbols.punch_clock_rounded, "Punch Clock", ["punch", "clock"]),
    _I("watch_later", Symbols.watch_later_rounded, "Watch Later", ["watch", "later"]),
    _I("bookmarks", Symbols.bookmarks_rounded, "Bookmarks", ["bookmarks"]),
    _I("bookmark_heart", Symbols.bookmark_heart_rounded, "Bookmark Heart", ["bookmark", "heart"]),
    _I("bookmark_star", Symbols.bookmark_star_rounded, "Bookmark Star", ["bookmark", "star"]),
    _I("lock_clock", Symbols.lock_clock_rounded, "Lock Clock", ["lock", "clock"]),
    _I("shield_person", Symbols.shield_person_rounded, "Shield Person", ["shield", "person"]),
    _I("shield_with_heart", Symbols.shield_with_heart_rounded, "Shield With Heart", ["shield", "with", "heart"]),
    _I("pan_tool", Symbols.pan_tool_rounded, "Pan Tool", ["pan", "tool"]),
    _I("restore", Symbols.restore_rounded, "Restore", ["restore"]),
    _I("other_admission", Symbols.other_admission_rounded, "Other Admission", ["other", "admission"]),
  ]),
];

final List<MaterialIconForCategory> materialIconCatalog = [
  for (MaterialIconSection section in materialIconSections) ...section.icons
];
